"""empty message

Revision ID: 226329cae96c
Revises: d3a9573e16e4
Create Date: 2024-06-01 17:57:47.695315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226329cae96c'
down_revision = 'd3a9573e16e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_paper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_question',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['test_paper.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['choicequestion.id'], ),
    sa.PrimaryKeyConstraint('paper_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_question')
    op.drop_table('test_paper')
    # ### end Alembic commands ###
