"""empty message

Revision ID: 349123aba76b
Revises: afac369cf54b
Create Date: 2024-05-31 17:16:41.120757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349123aba76b'
down_revision = 'afac369cf54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('identity')

    # ### end Alembic commands ###
