"""empty message

Revision ID: 916eaffdd326
Revises: ad814bfc2e8d
Create Date: 2024-06-01 20:39:53.245094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '916eaffdd326'
down_revision = 'ad814bfc2e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('choice', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.String(length=10), nullable=False))
        batch_op.drop_column('answers')
        batch_op.drop_column('right_answer')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('right_answer', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('answers', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('answer')
        batch_op.drop_column('choice')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
