"""empty message

Revision ID: a9ccf4f23bd9
Revises: f603dd9ca880
Create Date: 2024-06-01 20:36:18.499322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9ccf4f23bd9'
down_revision = 'f603dd9ca880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('choice', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('difficulty', sa.Integer(), nullable=False))
        batch_op.drop_column('answers')
        batch_op.drop_column('right_answer')
        batch_op.drop_column('id')
        batch_op.drop_column('dificulty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dificulty', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('right_answer', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('answers', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('difficulty')
        batch_op.drop_column('answer')
        batch_op.drop_column('choice')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
