"""empty message

Revision ID: ad814bfc2e8d
Revises: a9ccf4f23bd9
Create Date: 2024-06-01 20:37:22.698301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad814bfc2e8d'
down_revision = 'a9ccf4f23bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('answers', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('right_answer', sa.String(length=10), nullable=False))
        batch_op.drop_column('number')
        batch_op.drop_column('answer')
        batch_op.drop_column('choice')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choice', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('answer', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('right_answer')
        batch_op.drop_column('answers')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
