"""empty message

Revision ID: afac369cf54b
Revises: fe1d659c2a49
Create Date: 2024-05-31 16:34:32.575940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afac369cf54b'
down_revision = 'fe1d659c2a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('answers', sa.String(length=200), nullable=False),
    sa.Column('right_answer', sa.String(length=10), nullable=False),
    sa.Column('dificulty', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
