"""empty message

Revision ID: d3a9573e16e4
Revises: a5ac3e9d6b0b
Create Date: 2024-06-01 17:06:13.692338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3a9573e16e4'
down_revision = 'a5ac3e9d6b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('join_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('register_time')

    # ### end Alembic commands ###
