"""empty message

Revision ID: f603dd9ca880
Revises: 349123aba76b
Create Date: 2024-05-31 17:30:32.036663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f603dd9ca880'
down_revision = '349123aba76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('identity',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('identity',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
